### ISSUE TITLE
Release to Maven Central

### ISSUE THREAD

**Issue by asarkar** [devcsrj/slf4j-okhttp3-logging-interceptor#2]
Why don't you release this to Maven Central instead of some obscure repo? It seems it's not available.

```
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':compile'.
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.github.devcsrj:slf4j-okhttp3-logging-interceptor:1.0.0.
```

**Comment by devcsrj** [comment]
Hi! 

Looks like [jitpack.io](http://jitpack.io) is down at the moment, hence the exception you're getting.

> ..instead of some obscure repo

That's harsh :rofl: Jitpack was the easiest way I could deploy artifacts hosted on github. I'll try to configure publishing to Maven Central within the day if I find time.

**Comment by asarkar** [comment]
> try to configure publishing to Maven Central

Thank you, and I think you will see more adoption that way.

> within the day

That's not necessary, and may not be practical if you don't already have an account with them, which takes a day or two to set up.

**Comment by devcsrj** [comment]
The project is now on the [oss.sonatype](https://oss.sonatype.org/service/local/repositories/releases/content/com/github/devcsrj/slf4j-okhttp3-logging-interceptor/1.0.0)! I have updated the README to remove the jitpack references. Thank you!
